# flake8: noqa
# Generated by Django 3.2.25 on 2024-10-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250, unique=True)),
                ('answer', models.TextField(max_length=500, unique=True)),
            ],
        ),
    ]
