# Generated by Django 3.2.25 on 2024-09-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='recommendations',
        ),
        migrations.AddField(
            model_name='product',
            name='recommendations',
            field=models.ManyToManyField(blank=True, related_name='_products_product_recommendations_+', to='products.Product'),
        ),
    ]
