# Generated by Django 3.2.25 on 2024-09-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20240922_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='lifespan',
            field=models.CharField(choices=[('annual', 'Annual'), ('biennial', 'Biennial'), ('perennial', 'Perennial')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='light_exposure',
            field=models.CharField(choices=[('full_sun', 'Full Sun'), ('partial_shade', 'Partial Shade'), ('shade', 'Shade')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='soil_drainage',
            field=models.CharField(choices=[('well_drained', 'Well-drained'), ('poorly_drained', 'Poorly-drained'), ('moist', 'Moist')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('seeds', 'Seeds'), ('bulbs', 'Bulbs')], max_length=50),
        ),
    ]
